### PR TITLE
Style all asides in techdocs nicely, not just top level ones

### PR DESCRIPTION
**Pull request by lucas42**
At the moment, any aside inside another element (eg list item) doesn't get any style.  I'd like to be able to have nice looking asides in my lists.

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Let's have @kaelig look at this as there might be a reason for that that I don't know of

**Comment by matthew-andrews** [comment]
Noooo…

**Comment by AlbertoElias** [comment]
@matthew-andrews :question:

**Comment by kaelig** [comment]
Not sure an aside in a list is very semantic but couldn't you already achieve that by adding the `o-techdocs-content` class to the `<li>` element?

**Comment by matthew-andrews** [comment]
I believe this is to do with CMS's not being able to have classes on elements (one of the few exceptions to the _everything-must-be-a-class_ rule)

http://origami.ft.com/docs/syntax/scss/#naming-conventions-and-encapsulation

However I think an alternative solution would be for there to be two selectors for asides…… something like……
```css
.o-techdocs__aside {
  @include oTechdocsAside;
}

...
    > aside {
      @include oTechdocsAside
    }
...
```

**Comment by matthew-andrews** [comment]
If you just style all `asides` within a namespace……… well…… it's quite leaky.

**Comment by lucas42** [comment]
Adding the `o-techdocs-content` class to the `<li>` element causes the margins of that item to become inconsistent with the other items in the list.

What's the semantically correct way of marking text as tangentially relevant to a particular item in a list?

I just want all my asides to look the same!

**Comment by kaelig** [comment]
I agree with Matt, but I'm fine with this change, the use cases are limited (it's not consumer facing), and all the selectors in `o-techdocs-content` already are leaky.

:+1:

**Comment by matthew-andrews** [comment]
ah yes…… true

**Pull request merged**
